"use client";

import type { Summary } from "@/types";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { CheckCircle, Circle, AlertCircle, User, Lightbulb, Target, ListChecks } from "lucide-react";

export function SummaryPanel({
  summary,
  onRegenerate,
}: {
  summary: Summary;
  onRegenerate?: () => void;
}) {
  if (!summary) {
    return (
      <div className="text-center py-8 text-gray-500">
        No summary available
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <Card>
        <CardContent className="p-6">
          <div className="flex items-start justify-between">
            <div>
              <h2 className="text-2xl font-bold text-gray-900">
                {summary.ai_title || "Meeting Summary"}
              </h2>
              <p className="text-sm text-gray-500 mt-1">
                Generated by {summary.model_used}
              </p>
            </div>
            {onRegenerate && (
              <Button variant="outline" size="sm" onClick={onRegenerate}>
                Regenerate
              </Button>
            )}
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Attendees */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <User className="h-4 w-4" />
              Attendees
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {summary.attendees?.map((a, i) => (
                <Badge key={i} variant="default">
                  {a.name}
                  {a.is_guest && " (Guest)"}
                </Badge>
              )) || <span className="text-sm text-gray-400">None listed</span>}
            </div>
          </CardContent>
        </Card>

        {/* Action Items */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <ListChecks className="h-4 w-4" />
              Action Items
            </CardTitle>
          </CardHeader>
          <CardContent>
            {summary.action_items?.length ? (
              <ul className="space-y-2">
                {summary.action_items.map((item, i) => (
                  <li key={i} className="flex items-start gap-2">
                    {item.status === "done" ? (
                      <CheckCircle className="h-4 w-4 text-green-500 mt-0.5 shrink-0" />
                    ) : (
                      <Circle className="h-4 w-4 text-gray-300 mt-0.5 shrink-0" />
                    )}
                    <div>
                      <p className="text-sm text-gray-800">{item.description}</p>
                      {item.assignee && (
                        <p className="text-xs text-gray-500">Assignee: {item.assignee}</p>
                      )}
                    </div>
                  </li>
                ))}
              </ul>
            ) : (
              <span className="text-sm text-gray-400">No action items</span>
            )}
          </CardContent>
        </Card>

        {/* Key Points */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Lightbulb className="h-4 w-4" />
              Key Discussion Points
            </CardTitle>
          </CardHeader>
          <CardContent>
            {summary.key_points?.length ? (
              <ul className="space-y-3">
                {summary.key_points.map((kp, i) => (
                  <li key={i}>
                    {kp.topic && (
                      <p className="text-sm font-medium text-gray-700">{kp.topic}</p>
                    )}
                    <p className="text-sm text-gray-600">{kp.description}</p>
                  </li>
                ))}
              </ul>
            ) : (
              <span className="text-sm text-gray-400">No key points</span>
            )}
          </CardContent>
        </Card>

        {/* Decisions */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Target className="h-4 w-4" />
              Decisions
            </CardTitle>
          </CardHeader>
          <CardContent>
            {summary.decisions?.length ? (
              <ul className="space-y-3">
                {summary.decisions.map((d, i) => (
                  <li key={i} className="flex items-start gap-2">
                    {d.consensus ? (
                      <CheckCircle className="h-4 w-4 text-green-500 mt-0.5 shrink-0" />
                    ) : (
                      <AlertCircle className="h-4 w-4 text-yellow-500 mt-0.5 shrink-0" />
                    )}
                    <div>
                      <p className="text-sm text-gray-800">{d.description}</p>
                      {d.made_by && (
                        <p className="text-xs text-gray-500">By: {d.made_by}</p>
                      )}
                    </div>
                  </li>
                ))}
              </ul>
            ) : (
              <span className="text-sm text-gray-400">No decisions recorded</span>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Next Agenda */}
      {summary.next_agenda && (
        <Card>
          <CardHeader>
            <CardTitle>Next Meeting Agenda</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-gray-700 whitespace-pre-wrap">{summary.next_agenda}</p>
          </CardContent>
        </Card>
      )}

      {/* Additional Notes */}
      {summary.additional_notes && (
        <Card>
          <CardHeader>
            <CardTitle>Additional Notes</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-gray-700 whitespace-pre-wrap">{summary.additional_notes}</p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
