"use client";

import { useState } from "react";
import type { Meeting, Summary } from "@/types";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  CheckCircle,
  Circle,
  AlertCircle,
  User,
  Lightbulb,
  Target,
  ListChecks,
  FileText,
  Copy,
  Download,
} from "lucide-react";
import { MeetingMinutesMeta } from "./MeetingMinutesMeta";

export function SummaryPanel({
  summary,
  meeting,
  onRegenerate,
  regenerating,
  regenerateMessage,
  onUpdateMeeting,
  onExportMinutes,
}: {
  summary: Summary;
  meeting?: Meeting;
  onRegenerate?: () => void;
  regenerating?: boolean;
  regenerateMessage?: string;
  onUpdateMeeting?: (data: {
    host?: string | null;
    recorder_unit?: string | null;
    meeting_location?: string | null;
  }) => Promise<void>;
  onExportMinutes?: () => Promise<void>;
}) {
  const [exportingMinutes, setExportingMinutes] = useState(false);
  const [copied, setCopied] = useState(false);

  if (!summary) {
    return (
      <div className="text-center py-8 text-gray-500">
        No summary available
      </div>
    );
  }

  const handleCopyMinutes = async () => {
    if (!summary.formal_minutes) return;
    await navigator.clipboard.writeText(summary.formal_minutes);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportMinutes = async () => {
    if (!onExportMinutes) return;
    setExportingMinutes(true);
    try {
      await onExportMinutes();
    } finally {
      setExportingMinutes(false);
    }
  };

  return (
    <div className="space-y-6">
      {meeting && onUpdateMeeting && (
        <MeetingMinutesMeta meeting={meeting} onSave={onUpdateMeeting} />
      )}

      {/* Formal minutes */}
      <Card className="border-blue-100">
        <CardHeader>
          <div className="flex items-start justify-between gap-4">
            <CardTitle className="flex items-center gap-2 text-lg">
              <FileText className="h-5 w-5 text-blue-600" />
              会议纪要
            </CardTitle>
            <div className="flex flex-wrap gap-2 shrink-0">
              {summary.formal_minutes && (
                <>
                  <Button variant="outline" size="sm" onClick={handleCopyMinutes}>
                    <Copy className="h-4 w-4 mr-1" />
                    {copied ? "已复制" : "复制"}
                  </Button>
                  {onExportMinutes && (
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleExportMinutes}
                      loading={exportingMinutes}
                      disabled={exportingMinutes}
                    >
                      <Download className="h-4 w-4 mr-1" />
                      导出 Word
                    </Button>
                  )}
                </>
              )}
              {onRegenerate && (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={onRegenerate}
                  loading={regenerating}
                  disabled={regenerating}
                >
                  {regenerating ? "生成中…" : "重新生成"}
                </Button>
              )}
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {regenerateMessage && (
            <p className="text-sm text-blue-700 bg-blue-50 rounded-md px-3 py-2 mb-3">
              {regenerateMessage}
            </p>
          )}
          {regenerating && !summary.formal_minutes && (
            <p className="text-sm text-gray-600 mb-3">
              后台正在调用大模型撰写纪要，请勿关闭页面；完成后将自动刷新显示。
            </p>
          )}
          {summary.formal_minutes ? (
            <pre className="text-sm text-gray-800 whitespace-pre-wrap font-sans leading-relaxed">
              {summary.formal_minutes}
            </pre>
          ) : (
            <p className="text-sm text-gray-500">
              暂无正式纪要。请填写上方会议要素后点击「重新生成」，或等待处理完成后自动生成。
            </p>
          )}
        </CardContent>
      </Card>

      {/* Structured summary header */}
      <Card>
        <CardContent className="p-6">
          <div className="flex items-start justify-between">
            <div>
              <h2 className="text-xl font-bold text-gray-900">
                {summary.ai_title || "Meeting Summary"}
              </h2>
              <p className="text-sm text-gray-500 mt-1">
                Generated by {summary.model_used}
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <User className="h-4 w-4" />
              Attendees
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {summary.attendees?.map((a, i) => (
                <Badge key={i} variant="default">
                  {a.name}
                  {a.is_guest && " (Guest)"}
                </Badge>
              )) || <span className="text-sm text-gray-400">None listed</span>}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <ListChecks className="h-4 w-4" />
              Action Items
            </CardTitle>
          </CardHeader>
          <CardContent>
            {summary.action_items?.length ? (
              <ul className="space-y-2">
                {summary.action_items.map((item, i) => (
                  <li key={i} className="flex items-start gap-2">
                    {item.status === "done" ? (
                      <CheckCircle className="h-4 w-4 text-green-500 mt-0.5 shrink-0" />
                    ) : (
                      <Circle className="h-4 w-4 text-gray-300 mt-0.5 shrink-0" />
                    )}
                    <div>
                      <p className="text-sm text-gray-800">{item.description}</p>
                      {item.assignee && (
                        <p className="text-xs text-gray-500">Assignee: {item.assignee}</p>
                      )}
                    </div>
                  </li>
                ))}
              </ul>
            ) : (
              <span className="text-sm text-gray-400">No action items</span>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Lightbulb className="h-4 w-4" />
              Key Discussion Points
            </CardTitle>
          </CardHeader>
          <CardContent>
            {summary.key_points?.length ? (
              <ul className="space-y-3">
                {summary.key_points.map((kp, i) => (
                  <li key={i}>
                    {kp.topic && (
                      <p className="text-sm font-medium text-gray-700">{kp.topic}</p>
                    )}
                    <p className="text-sm text-gray-600">{kp.description}</p>
                  </li>
                ))}
              </ul>
            ) : (
              <span className="text-sm text-gray-400">No key points</span>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Target className="h-4 w-4" />
              Decisions
            </CardTitle>
          </CardHeader>
          <CardContent>
            {summary.decisions?.length ? (
              <ul className="space-y-3">
                {summary.decisions.map((d, i) => (
                  <li key={i} className="flex items-start gap-2">
                    {d.consensus ? (
                      <CheckCircle className="h-4 w-4 text-green-500 mt-0.5 shrink-0" />
                    ) : (
                      <AlertCircle className="h-4 w-4 text-yellow-500 mt-0.5 shrink-0" />
                    )}
                    <div>
                      <p className="text-sm text-gray-800">{d.description}</p>
                      {d.made_by && (
                        <p className="text-xs text-gray-500">By: {d.made_by}</p>
                      )}
                    </div>
                  </li>
                ))}
              </ul>
            ) : (
              <span className="text-sm text-gray-400">No decisions recorded</span>
            )}
          </CardContent>
        </Card>
      </div>

      {summary.next_agenda && (
        <Card>
          <CardHeader>
            <CardTitle>Next Meeting Agenda</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-gray-700 whitespace-pre-wrap">{summary.next_agenda}</p>
          </CardContent>
        </Card>
      )}

      {summary.additional_notes && (
        <Card>
          <CardHeader>
            <CardTitle>Additional Notes</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-gray-700 whitespace-pre-wrap">{summary.additional_notes}</p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
